const students = `[
    {
        "ID": 1001,
        "Full Name": "John Doe",
        "Speciality": "Software Engineering",
        "Status": "Active",
        "Mobile Phone": "555-1001",
        "Personal Email": "john.doe@example.com",
        "University Email": "j.doe@university.edu",
        "Co-op Start Date": "2024-01-15",
        "Co-op End Date": "2024-07-15",
        "Advisor": "Dr. Alice Johnson",
        "Early Report": "Bam",
        "Midway Report": "Boom",
        "Final Report": "Kaboom"
    },
    {
        "ID": 1002,
        "Full Name": "Jane Smith",
        "Speciality": "Data Science",
        "Status": "Active",
        "Mobile Phone": "555-1002",
        "Personal Email": "jane.smith@example.com",
        "University Email": "j.smith@university.edu",
        "Co-op Start Date": "2024-02-01",
        "Co-op End Date": "2024-08-01",
        "Advisor": "Dr. Alice Johnson",
        "Early Report": "hm",
        "Midway Report": "Bom",
        "Final Report": ""
    },
    {
        "ID": 1003,
        "Full Name": "Michael Johnson",
        "Speciality": "Cybersecurity",
        "Status": "Active",
        "Mobile Phone": "555-1003",
        "Personal Email": "michael.johnson@example.com",
        "University Email": "m.johnson@university.edu",
        "Co-op Start Date": "2024-03-01",
        "Co-op End Date": "2024-09-01",
        "Advisor": "Dr. Alice Johnson",
        "Early Report": "",
        "Midway Report": "",
        "Final Report": ""
    },
    {
        "ID": 1004,
        "Full Name": "Emily Davis",
        "Speciality": "Artificial Intelligence",
        "Status": "Active",
        "Mobile Phone": "555-1004",
        "Personal Email": "emily.davis@example.com",
        "University Email": "e.davis@university.edu",
        "Co-op Start Date": "2024-03-15",
        "Co-op End Date": "2024-09-15",
        "Advisor": "Dr. Alice Johnson",
        "Early Report": "",
        "Midway Report": "",
        "Final Report": ""
    },
    {
        "ID": 1005,
        "Full Name": "David Brown",
        "Speciality": "Machine Learning",
        "Status": "Active",
        "Mobile Phone": "555-1005",
        "Personal Email": "david.brown@example.com",
        "University Email": "d.brown@university.edu",
        "Co-op Start Date": "2024-04-01",
        "Co-op End Date": "2024-10-01",
        "Advisor": "Dr. Alice Johnson",
        "Early Report": "",
        "Midway Report": "",
        "Final Report": ""
    },
    {
        "ID": 1006,
        "Full Name": "Sophia Wilson",
        "Speciality": "Software Engineering",
        "Status": "Active",
        "Mobile Phone": "555-1006",
        "Personal Email": "sophia.wilson@example.com",
        "University Email": "s.wilson@university.edu",
        "Co-op Start Date": "2024-04-15",
        "Co-op End Date": "2024-10-15",
        "Advisor": "Dr. John Carter",
        "Early Report": "",
        "Midway Report": "",
        "Final Report": ""
    },
    {
        "ID": 1007,
        "Full Name": "Matthew Martinez",
        "Speciality": "Data Science",
        "Status": "Active",
        "Mobile Phone": "555-1007",
        "Personal Email": "matthew.martinez@example.com",
        "University Email": "m.martinez@university.edu",
        "Co-op Start Date": "2024-05-01",
        "Co-op End Date": "2024-11-01",
        "Advisor": "Dr. John Carter",
        "Early Report": "",
        "Midway Report": "",
        "Final Report": ""
    },
    {
        "ID": 1008,
        "Full Name": "Olivia Clark",
        "Speciality": "Cybersecurity",
        "Status": "Active",
        "Mobile Phone": "555-1008",
        "Personal Email": "olivia.clark@example.com",
        "University Email": "o.clark@university.edu",
        "Co-op Start Date": "2024-05-15",
        "Co-op End Date": "2024-11-15",
        "Advisor": "Dr. John Carter",
        "Early Report": "",
        "Midway Report": "",
        "Final Report": ""
    },
    {
        "ID": 1009,
        "Full Name": "Lucas Lee",
        "Speciality": "Artificial Intelligence",
        "Status": "Active",
        "Mobile Phone": "555-1009",
        "Personal Email": "lucas.lee@example.com",
        "University Email": "l.lee@university.edu",
        "Co-op Start Date": "2024-06-01",
        "Co-op End Date": "2024-12-01",
        "Advisor": "Dr. John Carter",
        "Early Report": "",
        "Midway Report": "",
        "Final Report": ""
    },
    {
        "ID": 1010,
        "Full Name": "Charlotte Lewis",
        "Speciality": "Machine Learning",
        "Status": "Active",
        "Mobile Phone": "555-1010",
        "Personal Email": "charlotte.lewis@example.com",
        "University Email": "c.lewis@university.edu",
        "Co-op Start Date": "2024-06-15",
        "Co-op End Date": "2024-12-15",
        "Advisor": "Dr. John Carter",
        "Early Report": "",
        "Midway Report": "",
        "Final Report": ""
    },
    {
     "ID": 1011,
        "Full Name": "Benjamin Walker",
        "Speciality": "Software Engineering",
        "Status": "Active",
        "Mobile Phone": "555-1011",
        "Personal Email": "benjamin.walker@example.com",
        "University Email": "b.walker@university.edu",
        "Co-op Start Date": "2024-01-01",
        "Co-op End Date": "2024-07-01",
        "Advisor": "Dr. John Carter",
        "Early Report": "",
        "Midway Report": "",
        "Final Report": ""
    },
    {
        "ID": 1012,
        "Full Name": "Amelia Hall",
        "Speciality": "Data Science",
        "Status": "Active",
        "Mobile Phone": "555-1012",
        "Personal Email": "amelia.hall@example.com",
        "University Email": "a.hall@university.edu",
        "Co-op Start Date": "2024-07-15",
        "Co-op End Date": "2025-01-15",
        "Advisor": "Dr. Emma Williams",
        "Early Report": "",
        "Midway Report": "",
        "Final Report": ""
    },
    {
        "ID": 1013,
        "Full Name": "Logan Young",
        "Speciality": "Cybersecurity",
        "Status": "Active",
        "Mobile Phone": "555-1013",
        "Personal Email": "logan.young@example.com",
        "University Email": "l.young@university.edu",
        "Co-op Start Date": "2024-08-01",
        "Co-op End Date": "2025-02-01",
        "Advisor": "Dr. Emma Williams",
        "Early Report": "",
        "Midway Report": "",
        "Final Report": ""
    },
    {
        "ID": 1014,
        "Full Name": "Grace Hernandez",
        "Speciality": "Artificial Intelligence",
        "Status": "Active",
        "Mobile Phone": "555-1014",
        "Personal Email": "grace.hernandez@example.com",
        "University Email": "g.hernandez@university.edu",
        "Co-op Start Date": "2024-08-15",
        "Co-op End Date": "2025-02-15",
        "Advisor": "Dr. Emma Williams",
        "Early Report": "",
        "Midway Report": "",
        "Final Report": ""
    },
    {
        "ID": 1015,
        "Full Name": "James King",
        "Speciality": "Machine Learning",
        "Status": "Active",
        "Mobile Phone": "555-1015",
        "Personal Email": "james.king@example.com",
        "University Email": "j.king@university.edu",
        "Co-op Start Date": "2024-09-01",
        "Co-op End Date": "2025-03-01",
        "Advisor": "Dr. Emma Williams",
        "Early Report": "",
        "Midway Report": "",
        "Final Report": ""
    }
]`;

// Parse the JSON string into an object
const studentDataArr = JSON.parse(students);

// Export the student data array
export { studentDataArr };
